### ISSUE TITLE
Can not install sniffer in Windows 10

### ISSUE THREAD

**Issue by kidozh** [dilawar/sniffer#4]
I try to install code-sniffer by source code in Windows but it raise a error related to environment variables 'HOME'.
I do not know how could I set this value.

BTW,it can install on Ubuntu.And I check environment variables 'HOME' which is '/home/ubuntu/'.

**Comment by dilawar** [comment]
I do not have a window environment to test it. Even if this issue is fixed, I am
not sure it will run on Windows without further tweaking. There is no plan to
make it windows compatible.

On Windows, You can run this application under cygwin https://www.cygwin.com .
It should run just fine.


--

**Comment by dilawar** [comment]
Try it under `bash` which is basically ubuntu in Windows.
https://msdn.microsoft.com/en-us/commandline/wsl/about
